---
title: "Get FatT transcripts"
author: "Nathaniel Olin"
date: "`r date()`"
output: github_document
---

```{r setup}
library(tidyverse)
library(googledrive)
library(googlesheets4)
sheets_auth(email = Sys.getenv("email"))

if(! "transcripts" %in% list.files())
  dir.create("transcripts")
```

# Download transcripts

## Get episode URLs

```{r get-list}
dat <- read_csv("meta.csv")
```

## Save transcripts to file

```{r}
# Remove locked file
dat[dat$url == "https://drive.google.com/open?id=19CSVitxMRtKKXr8m4swuczgAHtwcTT6sEEZaxSzQpgI"] <- NA

for(i in seq_along(dat$url)){
  if(!is.na(dat$url[i]))
    drive_download(as_id(dat$url[i]), path = sprintf("transcripts/%s.txt", i))
}
```


# Code additional metadata

## Code season names

```{r seasons}
dat <- dat %>%
  mutate(season = str_replace_all(
    episode_name, "^(.*?)( [0-9-]*):.*", "\\1"))

# Fix unnumbered episode
dat$season[dat$season == "Autumn in Hieron: Holiday Special"] <- "Autumn in Hieron"

# Stick to main seasons
dat <- dat %>%
  filter(season %in% c(
    "Autumn in Hieron", "COUNTER/Weight", 
    "Marielda", "Winter in Hieron", 
    "Twilight Mirage", "Spring in Hieron"))

dat %>% count(season)
```

## Code episode numbers

```{r ep-nums}
dat <- dat %>%
  mutate(episode_number = as.numeric(str_replace_all(
    episode_name, "^(.*? )([0-9-]*):.*", "\\2")))

dat$episode_number[str_detect(dat$episode_name, "Autumn in Hieron: Holiday Special")] <- NA
```

## Code episode names

```{r ep-names}
dat <- dat %>%
  mutate(episode_name = str_replace_all(
    episode_name, "^(.*? )([0-9-]*): (.*)", "\\3"))
```

# Write out

```{r write}
dat %>%
  select(season, episode_number, episode_name, minutes, url) %>%
  print() %>%
  write_csv("meta.csv")
```

